/**
 * Token Usage Types Contract
 * Feature: 009-token-usage
 *
 * These interfaces define the public API for token usage data.
 * To be added to src/core/types.ts and src/lib/types.ts.
 */

// ============================================================================
// Core Types (src/core/types.ts)
// ============================================================================

/**
 * Token consumption for a single message.
 * Present only when token data is available (non-zero values).
 */
export interface TokenUsage {
  /** Input tokens consumed by the request */
  inputTokens: number;
  /** Output tokens generated by the response */
  outputTokens: number;
}

/**
 * Context window state at message creation time.
 * Present only on user messages with this data.
 */
export interface ContextWindowStatus {
  /** Number of tokens used in context window */
  tokensUsed: number;
  /** Maximum context window size */
  tokenLimit: number;
  /** Percentage of context window remaining (0-100) */
  percentageRemaining: number;
}

/**
 * Model information for an assistant message.
 */
export interface ModelInfo {
  /** Model name (e.g., "claude-4.5-opus-high-thinking") */
  name: string;
}

/**
 * Timing information for an assistant message.
 */
export interface TimingInfo {
  /** Response duration in milliseconds */
  durationMs: number;
}

/**
 * Aggregated usage data for an entire session.
 */
export interface SessionUsage {
  /** Context tokens currently used in session */
  contextTokensUsed?: number;
  /** Context window limit for the session */
  contextTokenLimit?: number;
  /** Context window usage percentage (0-100) */
  contextUsagePercent?: number;
  /** Sum of input tokens across all messages */
  totalInputTokens?: number;
  /** Sum of output tokens across all messages */
  totalOutputTokens?: number;
}

// ============================================================================
// Extended Message Interface (additions to existing Message)
// ============================================================================

/**
 * Extended Message interface with token usage fields.
 * These fields are OPTIONAL - only present when data exists.
 */
export interface MessageWithUsage {
  // ... existing Message fields ...

  /** Token usage for this message (optional, present when data available) */
  tokenUsage?: TokenUsage;

  /** Model that generated this response (optional, assistant messages only) */
  model?: string;

  /** Response duration in milliseconds (optional, assistant messages only) */
  durationMs?: number;

  /** Context window status at creation (optional, user messages only) */
  contextWindow?: ContextWindowStatus;
}

// ============================================================================
// Extended Session Interface (additions to existing Session/ChatSession)
// ============================================================================

/**
 * Extended Session interface with usage summary.
 */
export interface SessionWithUsage {
  // ... existing Session/ChatSession fields ...

  /** Aggregated usage data for the session (optional) */
  usage?: SessionUsage;
}

// ============================================================================
// CLI Display Types
// ============================================================================

/**
 * Badge display data for CLI output.
 * Format: [model input→output duration]
 * Example: [claude-4.5-opus 131k→6k 2.3s]
 */
export interface UsageBadge {
  /** Model name (shortened for display) */
  model?: string;
  /** Formatted input tokens (e.g., "131k") */
  inputTokens?: string;
  /** Formatted output tokens (e.g., "6k") */
  outputTokens?: string;
  /** Formatted duration (e.g., "2.3s") */
  duration?: string;
}
